### ISSUE TITLE
Add validation to the frontend text box to only receive urls input

### ISSUE THREAD

**Issue by Maleehak** [Maleehak/BriefMe#1]
Currently the text box receives any kind of input and send a call to backend. Only allow Youtube urls to be accepted
<img width="892" alt="Screenshot 2024-04-29 at 5 27 13 PM" src="https://github.com/Maleehak/BriefMe/assets/39943018/d476c4c1-89fb-410d-93e0-8cc63c0e465b">

**Comment by Bhanubediya** [comment]
Hi @Maleehak can I work on this ?

**Comment by Maleehak** [comment]
Sure, assigning this issue to you

**Comment by Bhanubediya** [comment]
Hi @Maleehak one more question you want only you tube videos or youtube shorts too?

and also I just made a slight border radius change on search bar to make it look good. I f u agree I will keep or else I will revert it.

kindly check both images.
<img width="938" alt="brief me search bar " src="https://github.com/Maleehak/BriefMe/assets/38509248/c2e59212-238b-43e7-8737-be559ba9393d">
<img width="960" alt="validation" src="https://github.com/Maleehak/BriefMe/assets/38509248/dcbf6212-a68b-4fa2-9071-0e40f605bfa1">

**Comment by Maleehak** [comment]
@Bhanubediya , for now the backend works for Youtube videos only so what you did is fine. The search bar looks better now too IMO. Kindly check why the left section image is breaking.

**Comment by Bhanubediya** [comment]
> @Bhanubediya , for now the backend works for Youtube videos only so what you did is fine. The search bar looks better now too IMO. Kindly check why the left section image is breaking.

Thanks just wanted to share one thing that I think the summarize button which is in yellow should be disabled initially and it should be enabled only when the user pastes a valid url.
Just an idea. using bootstrap for future front end development would be great.

**Comment by Maleehak** [comment]
Good suggestion. I'll create another issue with your feedback or you can work on it as part of this change.

**Comment by Maleehak** [comment]
PR merged. Closing this issue. Thanks for your help.
