### ISSUE TITLE
Improve mobile view of the application

### ISSUE THREAD

**Issue by Maleehak** [Maleehak/BriefMe#2]
Mobile UI:

<img width="248" alt="Screenshot 2024-05-02 at 7 31 16 PM" src="https://github.com/Maleehak/BriefMe/assets/39943018/19563c4a-a152-46f2-a492-4ff118c1f3fc">

**Comment by shubhankar-shandilya-india** [comment]
Hi @Maleehak I want to work on this issue
Tell me what is expected in mobile view and i will make it according to that
should i make it like 
left part->right part->footer in downward direction in mobile view
for now only right part is visible in the mobile view

**Comment by Maleehak** [comment]
Sorry for the the ambiguity. No, I don't want the user to scroll all the way down to enter the url and get the summary. I have updated the comment about how I want the mobile view. Please feel free to share the better idea if you have any. Assigning you this issue. @shubhankar-shandilya-india

**Comment by shubhankar-shandilya-india** [comment]
HI @Maleehak i feel some styles and coding practices are not recommended which are used in the project can i transform it and make a better ui in mobile view 

Also footer will be required for sure in mobile view as well and it should be a different component rather then having this in left component

**Comment by Maleehak** [comment]
Sure, please go ahead. Please attach screenshots of both mobile and web view in the PR once you complete the task @shubhankar-shandilya-india
