### ISSUE TITLE
Disable Submit Button

### ISSUE THREAD

**Issue by Maleehak** [Maleehak/BriefMe#5]
Summarize button which is in yellow should be disabled initially and it should be enabled only when the user pastes a valid url.

<img width="892" alt="Screenshot 2024-04-29 at 5 27 13 PM" src="https://github.com/Maleehak/BriefMe/assets/39943018/99c493f2-bff5-4610-b468-12bf78619581">

**Comment by MukarramHaq** [comment]
Hello, I would like to work on this issue.

**Comment by Maleehak** [comment]
Hi @MukarramHaq , assigned you the issue. Please go ahead with the task

**Comment by Maleehak** [comment]
PR #6 is merged. Closing this issue
